version: '2'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - /Volumes/miguel/Docker/htdocs:/var/www/html/web
    container_name: dev-env
    
  db:
    image: mysql:5.7
    volumes:
      - /Volumes/miguel/Docker/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
