version: '2'

services:
  web:
    build: .
    ports:
      - "80:80"
    links: 
      - db
    volumes:
      - $PWD/www:/var/www/html/web
    container_name: dev-env
    
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - $PWD/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
