version: '2'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    links: 
      - db
    volumes:
      - /Applications/XAMPP/xamppfiles/htdocs/byc-mineduc01-ges:/var/www/html
    container_name: tide-dev-env
    
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - /Applications/XAMPP/xamppfiles/htdocs/test/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    container_name: db-mysql
